language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build
  - echo "sinix.dev" > dist/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN
  email: $GITHUB_EMAIL
  name: $GITHUB_NAME
  keep_history: true
  on:
    branch: master

